const questionData = [
  {
    question: `/img/q1_q.png`,
    mainImage: `/img/q1_main.png`,
    optionOneText: `/img/q1_a1.png`,
    optionTwoText: `/img/q1_a2.png`,
    optionOne: `E`,
    optionTwo: `I`,
  },
  {
    question: `/img/q2_q.png`,
    mainImage: `/img/q2_main.png`,
    optionOneText: `/img/q2_a1.png`,
    optionTwoText: `/img/q2_a2.png`,
    optionOne: `F`,
    optionTwo: `T`,
  },
  {
   question: `/img/q3_q.png`,
    mainImage: `/img/q3_main.png`,
    optionOneText: `/img/q3_a1.png`,
    optionTwoText: `/img/q3_a2.png`,
    optionOne: `S`,
    optionTwo: `N`,
  },
  {
    question: `/img/q4_q.png`,
    mainImage: `/img/q4_main.png`,
    optionOneText: `/img/q4_a1.png`,
    optionTwoText: `/img/q4_a2.png`,
    optionOne: `J`,
    optionTwo: `P`,
  },
  {
   question: `/img/q5_q.png`,
    mainImage: `/img/q5_main.png`,
    optionOneText: `/img/q5_a1.png`,
    optionTwoText: `/img/q5_a2.png`,
    optionOne: `J`,
    optionTwo: `P`,
  },
  {
    question: `/img/q6_q.png`,
    mainImage: `/img/q6_main.png`,
    optionOneText: `/img/q6_a1.png`,
    optionTwoText: `/img/q6_a2.png`,
    optionOne: `E`,
    optionTwo: `I`,
  },
  {
   question: `/img/q7_q.png`,
    mainImage: `/img/q7_main.png`,
    optionOneText: `/img/q7_a1.png`,
    optionTwoText: `/img/q7_a2.png`,
    optionOne: `E`,
    optionTwo: `I`,
  },
  {
  question: `/img/q8_q.png`,
    mainImage: `/img/q8_main.png`,
    optionOneText: `/img/q8_a1.png`,
    optionTwoText: `/img/q8_a2.png`,
    optionOne: `F`,
    optionTwo: `T`,
  },
  {
   question: `/img/q9_q.png`,
    mainImage: `/img/q9_main.png`,
    optionOneText: `/img/q9_a1.png`,
    optionTwoText: `/img/q9_a2.png`,
    optionOne: `S`,
    optionTwo: `N`,
  },
  {
   question: `/img/q10_q.png`,
    mainImage: `/img/q10_main.png`,
    optionOneText: `/img/q10_a1.png`,
    optionTwoText: `/img/q10_a2.png`,
    optionOne: `S`,
    optionTwo: `N,
    `,
  },

  {
   question: `/img/q11_q.png`,
    mainImage: `/img/q11_main.png`,
    optionOneText: `/img/q11_a1.png`,
    optionTwoText: `/img/q11_a2.png`,
    optionOne: `F`,
    optionTwo: `T`,
  },
  {
  question: `/img/q12_q.png`,
    mainImage: `/img/q12_main.png`,
    optionOneText: `/img/q12_a1.png`,
    optionTwoText: `/img/q12_a2.png`,
    optionOne: `J`,
    optionTwo: `P`,
  },
];

export default questionData;
